export const natureItems = [
  { id: 1, name: "White Pine Cone", category: "Trees", difficulty: "easy" },
  { id: 2, name: "Birch Bark", category: "Trees", difficulty: "easy" },
  { id: 3, name: "Red Maple Leaf", category: "Trees", difficulty: "easy" },
  { id: 4, name: "Moss-Covered Rock", category: "Nature", difficulty: "easy" },
  { id: 5, name: "Mushroom (any variety)", category: "Fungi", difficulty: "medium" },
  { id: 6, name: "Fern Frond", category: "Plants", difficulty: "easy" },
  { id: 7, name: "Deer Track", category: "Wildlife", difficulty: "medium" },
  { id: 8, name: "Hemlock Branch", category: "Trees", difficulty: "medium" },
  { id: 9, name: "Acorn", category: "Trees", difficulty: "easy" },
  { id: 10, name: "Wild Blueberry Bush", category: "Plants", difficulty: "medium" },
  { id: 11, name: "Cedar Branch", category: "Trees", difficulty: "easy" },
  { id: 12, name: "Lichen on Tree", category: "Nature", difficulty: "medium" },
  { id: 13, name: "Pine Needles (cluster)", category: "Trees", difficulty: "easy" },
  { id: 14, name: "Stream or Creek", category: "Water", difficulty: "medium" },
  { id: 15, name: "Bird Nest", category: "Wildlife", difficulty: "hard" },
  { id: 16, name: "Wild Flower", category: "Plants", difficulty: "medium" },
  { id: 17, name: "Spider Web", category: "Wildlife", difficulty: "medium" },
  { id: 18, name: "Fallen Log", category: "Nature", difficulty: "easy" },
];
